=== Craven-Biostat-Lab/GADGET/static/genelist.dtd
<!DOCTYPE genelist [
  <!ELEMENT genelist (description?, gene*)>
  
  <!ELEMENT description (query?, input_genes?, species, using_homologs, orderby?, limit?, offset?, errormessage?)>
  <!ELEMENT query (#PCDATA)>
  <!ELEMENT input_genes (input_gene+)>
  <!ELEMENT input_gene (entrez_id, symbol)>
  <!ELEMENT species (#PCDATA)>
  <!ELEMENT using_homologs (#PCDATA)>
  <!ELEMENT orderby (#PCDATA)>
  <!ELEMENT limit (#PCDATA)>
  <!ELEMENT offset (#PCDATA)>
  <!ELEMENT errormessage (#PCDATA)>
  
  <!ELEMENT gene (rank, f1_score, matching_abstracts, total_abstracts, adjusted_precision, p_value, symbol, name, synonyms?, db_refs, chromosome, map_location)>
  <!ELEMENT rank (#PCDATA)>
  <!ELEMENT f1_score (#PCDATA)>
  <!ELEMENT matching_abstracts (#PCDATA)>
  <!ELEMENT total_abstracts (#PCDATA)>
  <!ELEMENT adjusted_precision (#PCDATA)>
  <!ELEMENT p_value (#PCDATA)>
  <!ELEMENT symbol (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT synonyms (#PCDATA)>
  <!ELEMENT chromosome (#PCDATA)>
  <!ELEMENT map_location (#PCDATA)>
  
  <!ELEMENT db_refs (entrez_id, hgnc_id?, ensembl_id?, mim_id?, hprd_id?)>
  <!ELEMENT entrez_id (#PCDATA)>
  <!ELEMENT hgnc_id (#PCDATA)>
  <!ELEMENT ensembl_id (#PCDATA)>
  <!ELEMENT mim_id (#PCDATA)>
  <!ELEMENT hprd_id (#PCDATA)>
]>

=== Craven-Biostat-Lab/GADGET/genetext/templates/genelist.xml
<?xml version="1.0" ?>
<!DOCTYPE genelist SYSTEM "http://gadget.biostat.wisc.edu/static/genelist.dtd">
<genelist>
  <description>
    <query>{{ q }}</query>{% if orderby %}
    <orderby>{{ orderby }}</orderby>{% endif %}{% if limit %}
    <limit>{{ limit }}</limit>{% endif %}{% if offset %}
    <offset>{{ offset }}</offset>{% endif %}{% if errmsg %}
    <errormessage>{{ errmsg }}</errormessage>{% endif %}
  </description>
{% for g, p in genes %}  <gene>
    <rank>{{ forloop.counter|add:offset }}</rank>
    <f1_score>{{ g.f1_score|floatformat:-3 }}</f1_score>
    <matching_abstracts>{{ g.hits }}</matching_abstracts>
    <total_abstracts>{{ g.abstracts }}</total_abstracts>
    <adjusted_precision>{{ g.precision|floatformat:-3 }}</adjusted_precision>
    <p_value>{{ p }}</p_value>
    <symbol>{{ g.symbol }}</symbol>
    <name>{{ g.name }}</name>{% if g.synonyms %}
    <synonyms>{{ g.synonyms }}</synonyms>{% endif %}
    <db_refs>
      <entrez_id>{{ g.entrez_id }}</entrez_id>{% if g.hgnc_id %}
      <hgnc_id>{{ g.hgnc_id }}</hgnc_id>{% endif %}{% if g.ensembl_id %}
      <ensembl_id>{{ g.ensembl_id }}</ensembl_id>{% endif %}{% if g.mim_id %}
      <mim_id>{{ g.mim_id }}</mim_id>{% endif %}{% if g.hprd_id %}
      <hprd_id>{{ g.hprd_id }}</hprd_id>{% endif %}
    </db_refs>
    <chromosome>{{ g.chromosome }}</chromosome>
    <map_location>{{ g.map_location }}</map_location>
  </gene>{% endfor %}
</genelist>
